### ISSUE TITLE
Unplayable in latest update

### ISSUE THREAD

**Issue by CTOUT** [exochron/ToyBoxEnhanced#20]
A recent update (2.7/2.7.1?) has made the game unplayable with hundreds of LUA errors occurring for ToyBoxEnhanced.
Disabling ToyBoxEnhanced stopped this issue.

411x ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua:79: Usage: strcmputf8i(string1, string2)
[string "=[C]"]: in function `strcmputf8i'
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:79: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:57>
[string "=[C]"]: in function `sort'
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:57: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:41>
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:96: in function `FilterAndRefresh'
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:38: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:30>
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:145: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:124>

Locals:
(*temporary) = "Arrival of the Naaru"
(*temporary) = nil

**Comment by exochron** [comment]
It should be fixed in 2.7.2.
Feel free to reopen this issue if that's not the case.
