### ISSUE TITLE
Major fps lag when addon is enabled

### ISSUE THREAD

**Issue by vmwinckler** [exochron/ToyBoxEnhanced#22]
117x ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua:79: Usage: strcmputf8i(string1, string2)
[string "=[C]"]: in function `strcmputf8i'
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:79: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:57>
[string "=[C]"]: in function `sort'
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:57: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:41>
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:96: in function `FilterAndRefresh'
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:38: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:30>
[string "@ToyBoxEnhanced\ToyBoxEnhanced-2.7.1.lua"]:145: in function <ToyBoxEnhanced\ToyBoxEnhanced.lua:124>

Locals:
(*temporary) = nil
(*temporary) = nil

**Comment by exochron** [comment]
It should be fixed in 2.7.2.
Feel free to reopen this issue if that's not the case.
