### ISSUE TITLE
10.0 update, can't click on any toy

### ISSUE THREAD

**Issue by Toasty66** [exochron/ToyBoxEnhanced#31]
With the v10 ToyBoxEnhanced installed, I'm unable to click on any of the toys within the interface.  If I disable ToyBoxEnhanced and reload the UI, clicking is restored.  No lua errors were caught in bugsack.

**Comment by exochron** [comment]
It seems the default spell button behavior was updated in some way. So our buttons just don't do anything at the moment.
(some further read: https://github.com/Stanzilla/WoWUIBugs/issues/307#issuecomment-1294483631)

Honestly, I just don't know how to deal with this yet. :(

**Comment by exochron** [comment]
fixed with 2.12.1
