### ISSUE TITLE
Bug - New toy doesn't show until after reload

### ISSUE THREAD

**Issue by Taizunz** [exochron/ToyBoxEnhanced#41]
Title says it all.
Most recent case is after I acquired the toy "Whelps on Strings". Had to /reload to make it show up in the toy box.

It doesn't produce a lua error.

**Comment by exochron** [comment]
Thanks for reporting this bug. That can happen on some toys even without addon.
At least the Whelps should be now in the Toybox from the beginning with version 2.18.0 😃
