### ISSUE TITLE
Feature request: port to WoTLK Classic

### ISSUE THREAD

**Issue by Barov2** [exochron/ToyBoxEnhanced#43]
Now that WoTLK Classic (version 3.4.3) has a Toy Box like Retail, could you port Toy Box Enhanced  to WoTLK Classic? Thank you so much.

**Comment by exochron** [comment]
Honestly, I'm a bit surprised to see the Collections in Classic already. Originally the Toy Box was introduced in WoD. So I thought/hoped that I could postphone a classic version for a while longer.
Whelp, seems I was wrong. So I'm going to look into it. But it might take a while. :)

**Comment by exochron** [comment]
I've just whipped together a little working prototype.
Only problem is that I can't properly test it yet. I don't play classic. Therefore my DK has no toys yet. It's probably going to take a bit to collect a few. 🙈

**Comment by Barov2** [comment]
You have two vendors of toys in Dalaran, if you find a mage to tp you there:

- Breanni https://www.wowhead.com/wotlk/npc=28951/breanni
- Jepetto Joybuzz https://www.wowhead.com/wotlk/npc=29478/jepetto-joybuzz

(toys don't yet appear as such in the Wowhead database, but they are indeed toys)

**Comment by Barov2** [comment]
Also, an innkeeper can have toys as rewards for a 6-month subscription:

- [Goblin Gumbo Kettle](https://www.wowhead.com/wotlk/item=33219/goblin-gumbo-kettle): https://www.wowhead.com/wotlk/blue-tracker/news/us/world-of-warcraft-news-and-development-updates-23761710
- [Imp in a Ball](https://tbc.wowhead.com/item=32542/imp-in-a-ball): https://www.wowhead.com/wotlk/news/world-of-warcraft-six-month-subscription-includes-imp-in-a-ball-toy-for-burning-322435

**Comment by exochron** [comment]
... and [released](https://github.com/exochron/ToyBoxEnhanced/releases/tag/2.19). Thank you for your inspiration and help. 😃
