### ISSUE TITLE
Some variables are not exposed on Curseforge Localization

### ISSUE THREAD

**Issue by Barov2** [exochron/ToyBoxEnhanced#45]
On https://legacy.curseforge.com/wow/addons/toy-box-enhanced/localization/

At least the "Transport > Teleport" effect (it's the only one I see in Wrath Classic — I was able to translate all the others into French —, but there may be others in Retail).

**Comment by exochron** [comment]
Phew, thanks for finding that bug. And for translating in french! 🇫🇷 

For some texts I'm using snippets from the game. That keeps the translation list fairly small. :)
For the "Teleport" I was using the spell name of [[Teleport]](https://www.wowhead.com/spell=343127/teleport). But that particular spell doesn't exist yet in WotLK. So the english original text gets chosen as fallback. Luckily there are several other spells to choose from. So no prob :)

Well.. for Teleport at least. 
The same problem exists also for [[Statue]](https://www.wowhead.com/spell=88640/statue) and there are no direct alternatives in WotLK. So as alternativeI'm chosing [[Instant Statue]](https://www.wowhead.com/wotlk/spell=74890/instant-statue). There is only one Toy in that category anyway.

**Comment by Barov2** [comment]
Oh, I see the issue for Statue: we using the same word in French, so I didn't see that the word wasn't translated! But thanks for the explanations!
