### ISSUE TITLE
Toys missing for WotLK Classic

### ISSUE THREAD

**Issue by Barov2** [exochron/ToyBoxEnhanced#46]
Hi,

Some toys are missing in the WotLK version (btw, toys still do not appear as such in the WotLK Classic version of Wowhead):

- [Fishspeaker's Lucky Lure](https://www.wowhead.com/wotlk/item=198647/fishspeakers-lucky-lure) (unique to WotLK Classic, I believe)
- [Dark Portal](https://www.wowhead.com/wotlk/item=184871/dark-portal) (equivalent of [Dark Portal](https://www.wowhead.com/item=93672/dark-portal), but with another ID)
- [Path of Illidan](https://www.wowhead.com/wotlk/item=38233/path-of-illidan) (item 38233 doesn't appear to be a toy under Retail)

Also, wouldn't [Don Carlos' Famous Hat](https://www.wowhead.com/wotlk/item=38506/don-carlos-famous-hat) be better placed in the BC extension rather than WotLK? Same for [The Flag of Ownership](https://www.wowhead.com/tbc/item=38578/the-flag-of-ownership).

**Comment by exochron** [comment]
Thank you for your feedback. It's a bit diffucult for me to find added classic toys. So your help is really appreciated. 😃

I'm going to realease a new version with a patch probably tomorrow.

**Comment by exochron** [comment]
... and released in version [2.20](https://github.com/exochron/ToyBoxEnhanced/releases/tag/2.20). Have fun and Thank you 😄
