### ISSUE TITLE
[Bug] Double Entry in Tooltip of Faction

### ISSUE THREAD

**Issue by RAtwood90** [exochron/ToyBoxEnhanced#49]
Hello Mate! 

There are double Entrys for Faction Toys on some of them.

Example: 
![image](https://github.com/exochron/ToyBoxEnhanced/assets/73589071/b4c3a559-8529-42e6-93d1-cb439fb2709f)

May u can fix it? :)

**Comment by exochron** [comment]
I'm sorry, but I cant help you with that. That tooltip comes from the game client.
You can however write a bug report in game about that and hope for the best. :)
