### ISSUE TITLE
Operation Gnomeregan and Zalazane's Fall

### ISSUE THREAD

**Issue by Adal4** [exochron/ToyBoxEnhanced#53]
Two new toys in WotLK Classic, related to Operation Gnomeregan and Zalazane's Fall:

- [Darkspear Pride](https://www.wowhead.com/wotlk/item=54653)
- [Gnomeregan Pride](https://www.wowhead.com/wotlk/item=54651)

Thanks!

**Comment by exochron** [comment]
They already should be available. :)
