### ISSUE TITLE
Issue with elvui skin

### ISSUE THREAD

**Issue by AngelosNaoumis** [exochron/ToyBoxEnhanced#58]
ElvUI skin does not follow the colors of ElvUI
e.g.

![image](https://github.com/user-attachments/assets/13782f1d-0850-42b3-8f92-ca6b40b560a5)

Also maybe i could be good to skin buttons as well
![image](https://github.com/user-attachments/assets/27a68267-17f5-4535-8959-531f90fd6de1)

e.g.
![image](https://github.com/user-attachments/assets/5e614daa-c2ea-4dbc-8ce1-70bcea3f40f7)

**Comment by RAtwood90** [comment]
![image](https://github.com/user-attachments/assets/a6374517-1221-4b7f-8131-d243eb2500a0)

There is no Issue with that. Another Addon is causing that Issue or you are outdated.

**Comment by RAtwood90** [comment]
> If it follows elvui standard skinning it should be the same background color as set in ElvUI.
> 
> Right now its always black. So in reality in your case: ![image](https://private-user-images.githubusercontent.com/25444260/358267867-beebab14-bb2d-4128-b6da-77300f45f62e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTEwNjQsIm5iZiI6MTcyMzgxMDc2NCwicGF0aCI6Ii8yNTQ0NDI2MC8zNTgyNjc4NjctYmVlYmFiMTQtYmIyZC00MTI4LWI2ZGEtNzczMDBmNDVmNjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEyMTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OTUzZDRhMDVjN2MyOTA0N2EzM2UwMzhlMjYzZDYyYzg0YmJlZmM2MWRkYjRjYjE0NzkxMjI2NjQ5ZTY1MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X7QuRTv0lcPaUayNLhmRtxElsTjHr01MwshzCIj5Wh4) should be ![image](https://private-user-images.githubusercontent.com/25444260/358267833-f217e67d-82ea-4f2b-b518-314e45faf274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTEwNjQsIm5iZiI6MTcyMzgxMDc2NCwicGF0aCI6Ii8yNTQ0NDI2MC8zNTgyNjc4MzMtZjIxN2U2N2QtODJlYS00ZjJiLWI1MTgtMzE0ZTQ1ZmFmMjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEyMTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkN2RiZDQwMzAwY2Y2NGFmMDM1NDFhNzk0M2Y4NmM5MDMyZmRjMzNmOGVmNjIzYWE2NmJjMzRmNDNkNjQzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYV_MK4ldcUDcNixjQaA1oWM-VqRetA0CkDkk1J_TyE)

You already posted under my Ticket. And didn't read before posting.

![image](https://github.com/user-attachments/assets/244dca88-09ad-4506-a12d-d4ac6f062a8b)

It's impossible Bro. To make it Transparent.

**Comment by exochron** [comment]
Version 2.28 now comes without an extra background. :)
