### ISSUE TITLE
Filter LUA Error

### ISSUE THREAD

**Issue by RAtwood90** [exochron/ToyBoxEnhanced#60]
Message: Interface/AddOns/ToyBoxEnhanced/Filters.lua:24: attempt to call global 'GetSpellDescription' (a nil value)
Time: Thu Aug 15 16:18:11 2024
Count: 6
Stack: Interface/AddOns/ToyBoxEnhanced/Filters.lua:24: attempt to call global 'GetSpellDescription' (a nil value)
[string "@Interface/AddOns/ToyBoxEnhanced/Filters.lua"]:24: in function <Interface/AddOns/ToyBoxEnhanced/Filters.lua:12>
[string "@Interface/AddOns/ToyBoxEnhanced/Filters.lua"]:253: in function `FilterToys'
[string "@Interface/AddOns/ToyBoxEnhanced/ToyBoxEnhanced.lua"]:166: in function <Interface/AddOns/ToyBoxEnhanced/ToyBoxEnhanced.lua:138>

Locals: itemId = 147310
searchString = "bea"
_ = 147310
name = "Crate of Bobbers: Floating Totem"
_ = "Floating Totem"
spellId = 240802
(*temporary) = nil
(*temporary) = 240802
(*temporary) = "attempt to call global 'GetSpellDescription' (a nil value)"
ADDON = <table> {
 initialized = true
 settings = <table> {
 }
 UI = <table> {
 }
 Events = <table> {
 }
 TOYS_PER_PAGE = 18
 db = <table> {
 }
 L = <table> {
 }
 DataProvider = <table> {
 }
}

May did have something to do with the Pull Request you got in the last 2 Hours.

**Comment by exochron** [comment]
fixed with 2.26
