### ISSUE TITLE
(Feature Request) LDB Broker Option

### ISSUE THREAD

**Issue by Comettii** [exochron/ToyBoxEnhanced#64]
First of all, thank you very much for your magnificent work!

I would like to suggest adding the broker function, which would make it easier for all of us who use Titan Panel, ChocolateBar, ElvUI, to use, for example, favorite toys more quickly.

I don't know how this works, but I think this link explains how to make your plugin compatible with this functionality.
https://www.titanpanel.org/ldb.html

Thank you

**Comment by Comettii** [comment]
Wow, I would like to help a little better, but I'm just an ordinary user :( 
If it were possible to show the list of favorite toys as an activation shortcut, that would be amazing! I hope you can do it, I wish you the best of luck!
Thx again

**Comment by exochron** [comment]
added in Version 2.28. Have fun. I hope you like it :smile:
