### ISSUE TITLE
 attempt to call method 'SetPropagateMouseClicks' (a nil value)

### ISSUE THREAD

**Issue by Adal4** [exochron/ToyBoxEnhanced#68]
I get this lua error with the latest version (WoW Cataclysm, French client):

10x ToyBoxEnhanced/UI/LDB-Favorites.lua:11: attempt to call method 'SetPropagateMouseClicks' (a nil value)
[string "@ToyBoxEnhanced/UI/LDB-Favorites.lua"]:11: in function <ToyBoxEnhanced/UI/LDB-Favorites.lua:5>
[string "@ToyBoxEnhanced/UI/LDB-Favorites.lua"]:94: in function <ToyBoxEnhanced/UI/LDB-Favorites.lua:88>
[string "=[C]"]: ?
[string "@Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rfaceBlizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Blizzard_SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@ToyBoxEnhanced/ToyBoxEnhanced.lua"]:163: in function <ToyBoxEnhanced/ToyBoxEnhanced.lua:158>

Locals:
button = Button {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = Button {
 0 = <userdata>
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetPropagateMouseClicks' (a nil value)"

**Comment by exochron** [comment]
Oh, I see. Version 2.28 is not quite compatible with 4.4.0. It only supports 4.4.1.
This error only affects the databroker plugin.
So for now, you could just ignore this error and wait for 4.4.1. Or you can rollback to version 2.27. :)

**Comment by Adal4** [comment]
OK, thanks! :)

**Comment by exochron** [comment]
4.4.1 is now live. therefore the error should be gone :smile:

**Comment by Adal4** [comment]
Indeed, thanks!
