### ISSUE TITLE
TBE - Mega Macro issue (Turn off random toy macro autocreation)

### ISSUE THREAD

**Issue by NoNick96** [exochron/ToyBoxEnhanced#71]
Hello. I'm using Mega Macro addon to manage and sort all of my macros. It does it by altering already existing macros including TBE's random toy macro (1st pic). TBE then doesn't detect that the macro already exists and creates a new one, which is then again - modified by Mega Macro addon. This causes the macro to be created every time i log in or reload the UI and I end up with like 20 of them at the end of a play session (2nd pic). I'd like to request a feature to turn off the automated creation of the "Use random favorite toy" macro or allow the modification of it. I love TBE and cannot imagine playing without it.

![Wow_cq4UO9JGzD](https://github.com/user-attachments/assets/966e4349-9541-4186-8df7-d22df7e19f17)
![Wow_FGdVBT6cMv](https://github.com/user-attachments/assets/664cd2c2-f6f1-451c-9e06-9c1791ecccef)

**Comment by NoNick96** [comment]
This is how a modified macro looks like: 
![Wow_IbHS0fgGBa](https://github.com/user-attachments/assets/d73d9be8-7e21-4a19-9be4-f6ac2af52b00)

**Comment by exochron** [comment]
should be fixed with version 2.29
